export const METADATA_ROUTER_PATH = Symbol('METADATA_ROUTER_PATH');
export const METADATA_ROUTER_METHOD = Symbol('METADATA_ROUTER_METHOD');
export const METADATA_ROUTER_RENDER_VIEW = Symbol('METADATA_ROUTER_RENDER_VIEW');

export const METADATA_ROUTER_BODY_SCHAME = Symbol('METADATA_ROUTER_BODY_SCHAME');
export const METADATA_ROUTER_QUERY_SCHAME = Symbol('METADATA_ROUTER_QUERY_SCHAME');

export const METADATA_ROUTER_PARAMS = Symbol('METADATA_ROUTER_PARAMS');
export const METADATA_ROUTER_PARAM_OPTIONAL = Symbol('METADATA_ROUTER_PARAM_OPTIONAL');

export const METADATA_ROUTER_MIDDLEWARE = Symbol('METADATA_ROUTER_MIDDLEWARE');

export const METADATA_API_OPERATION = Symbol('METADATA_API_OPERATION');
export const METADATA_API_USETAGS = Symbol('METADATA_API_USETAGS');
export const METADATA_API_DESCRIPTION = Symbol('METADATA_API_DESCRIPTION');
