export const METADATA_ROUTER_PATH = Symbol('METADATA_ROUTER_PATH');
export const METADATA_ROUTER_METHOD = Symbol('METADATA_ROUTER_METHOD');

export const METADATA_ROUTER_PARAMS = Symbol('METADATA_ROUTER_PARAMS');

export const METADATA_ROUTER_MIDDLEWARE = Symbol('METADATA_ROUTER_MIDDLEWARE');
